### PR TITLE
Add ability to access named keychains in Mac OS.

### PR DESCRIPTION
**Pull request by nagasunilt**

### CODE REVIEW

**Comment by hwchen** [comment]
@nagasunilt can you add some docs in the readme for this? The code looks good to me.

**Comment by nagasunilt** [comment]
@hwchen just updated. lmk if anything is missing.

**Comment by hwchen** [comment]
hmmm... I just had another thought. How would you feel if this feature was put behind a feature flag, maybe something like `macos-unstable`, so that users would have to explicitly turn this feature on? It's one more way of setting this feature apart from the rest of the API which works across platforms.

**Comment by naga-cf** [comment]
@hwchen ok, added feature flag "macos-specify-keychain" which is used to conditional compile the new api `use_keychain()`.

**Comment by nagasunilt** [comment]
@hwchen ok, added feature flag "macos-specify-keychain" which is used to conditional compile the new api use_keychain().

**Comment by nagasunilt** [comment]
@hwchen Hello, can you please take a look at latest update and lmk if any changes are needed. Thanks!

**Comment by hwchen** [comment]
Sorry I've been quite busy lately, I'll take a look asap!

**Comment by naga-cf** [comment]
gentle bump!

**Comment by nagasunilt** [comment]
@hwchen any update?

**Comment by hwchen** [comment]
Hey @nagasunilt it looks like CI is failing on:
```
error[E0599]: no function or associated item named `use_keychain` found for struct `macos::Keyring<'_>` in the current scope

  --> src/macos.rs:72:22

   |

6  | pub struct Keyring<'a> {

   | ---------------------- function or associated item `use_keychain` not found for this

...

72 |             Keyring::use_keychain("testservice", "testuser", Path::new("/Library/Keychains/System.keychain"))

   |                      ^^^^^^^^^^^^

   |                      |

   |                      function or associated item not found in `macos::Keyring<'_>`

   |                      help: there is an associated function with a similar name: `get_keychain`
```

I think this means that there's some issue with the conditional `cfg` in the test. Do you know what the issue might be?

**Pull request merged**
