### PR TITLE
Added use of KeyringError::NoPasswordFound and KeyringError:NoBackendFound to windows code

### LINKED ISSUE #49: Can't tell if a secret exists on Windows
It looks to me like there's no way to get a `NoPasswordFound` from the Windows implementation which makes it hard to figure out if the library is failing or there's just no password set.

Long term maybe the API should be changed to return an `Option<T>` instead of returning an `Err` when there's no value?

### PR DESCRIPTION
**Pull request by phillipCouto**
This resolves #49 by allowing calling code to determine if the password was not found when getting or deleting the password.

### CODE REVIEW

**Comment by phillipCouto** [comment]
I am more than happy to flush out the error codes for the windows side but I figured I would just tackle these simple cases.

**Comment by hwchen** [comment]
Thanks very much for doing this. i'll take a look asap

**Comment by phillipCouto** [comment]
> Thanks very much for doing this. i'll take a look asap

No problem, more than happy to contribute 😊

**Comment by hwchen** [comment]
Thanks again for doing this, handling of nopasswordfound and nobackendfound is very helpful.

For the utf16 error, it would unfortunately be a breaking change right now (because the `Error` enum is exhaustive). Can you move the utf16 code to another PR? Otherwise the rest of the code is good to go.

(Also, I might want to see if the utf16 error can be rolled up with the utf8 error into what's currently called a `Parse` error).

**Comment by phillipCouto** [comment]
> Thanks again for doing this, handling of nopasswordfound and nobackendfound is very helpful.
> 
> For the utf16 error, it would unfortunately be a breaking change right now (because the `Error` enum is exhaustive). Can you move the utf16 code to another PR? Otherwise the rest of the code is good to go.
> 
> (Also, I might want to see if the utf16 error can be rolled up with the utf8 error into what's currently called a `Parse` error).

Done 😄 

Yeah I will make a new MR for handling the UTF16 error. I will try my hand at a single `Parse` for encoding errors.

**Comment by phillipCouto** [comment]
@hwchen just wanted to ping and see if you have any idea when you will be able to review this.

**Comment by hwchen** [comment]
Sorry, this looks good, thanks!

**Pull request merged**
